name: update
on:
   workflow_dispatch:
      input:
        tf-apply:
            type: boolean
            description: "Run terraform apply"
        aws-seconds:
            type: number
            default: 1000
            required: false
            description: "Duration in seconds"
        repo-to-deploy:
            description: "Sngle worksapce"
            required: false
            default: "CHINA"
            type: string
jobs:
    get-env:
       runs-on: ubuntu-latest
       steps:
          - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"  
          - run: echo "haha---${{ github.event.inputs.repo-to-deploy }}---"  
